# Generated by Django 5.2.1 on 2025-06-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_client_options_client_city_client_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="country",),
    ]
