# Generated by Django 5.2.1 on 2025-06-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_remove_client_country"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="address",),
    ]
