# Generated by Django 5.2.1 on 2025-06-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_remove_client_address"),
    ]

    operations = [
        migrations.RenameModel(old_name="Notes", new_name="Note",),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("in_progress", "In Progress"), ("completed", "Completed")],
                default="pending",
                max_length=20,
                null=True,
            ),
        ),
    ]
