# Generated by Django 5.2.1 on 2025-06-27 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_rename_notes_note_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="crm.client",
            ),
        ),
    ]
