# Generated by Django 5.2.1 on 2025-07-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_alter_task_client"),
    ]

    operations = [
        migrations.RenameModel(old_name="Task", new_name="Activity",),
    ]
