# Generated by Django 5.2.1 on 2025-07-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_rename_task_activity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note", old_name="task", new_name="activity",
        ),
    ]
