# Generated by Django 5.2.1 on 2025-07-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_rename_task_note_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="premium_amount",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
