# Generated by Django 5.2.1 on 2025-07-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_alter_policy_premium_amount"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="dark_mode_enabled",),
        migrations.AddField(
            model_name="userprofile",
            name="theme_preference",
            field=models.CharField(
                choices=[
                    ("auto", "Auto (System Default)"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                ],
                default="auto",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="policy_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("life", "Life"),
                    ("auto", "Auto"),
                    ("home", "Home"),
                    ("health", "Health"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
