# Generated by Django 5.2.1 on 2025-07-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_remove_userprofile_dark_mode_enabled_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="UserProfile", new_name="UserSettings",),
    ]
