# Generated by Django 5.2.1 on 2025-07-06 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_rename_userprofile_usersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
