# Generated by Django 5.2.1 on 2025-07-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_alter_usersettings_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="/default_img.png", null=True, upload_to="profiles/"
            ),
        ),
    ]
