# Generated by Django 5.2.1 on 2025-07-06 05:04

import crm.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0013_alter_usersettings_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="/default_img.png",
                null=True,
                upload_to=crm.models.models.image_upload,
            ),
        ),
    ]
