# Generated by Django 5.2.1 on 2025-07-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_alter_usersettings_profile_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["-due_date"],
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.RenameField(
            model_name="policy", old_name="provider", new_name="insurer",
        ),
    ]
