# Generated by Django 5.2.1 on 2025-07-17 20:03

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0015_alter_activity_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=prose.fields.RichTextField(blank=True, null=True),
        ),
    ]
