# Generated by Django 5.2.1 on 2025-09-14 18:49

import crm.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0016_alter_activity_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="policy_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("life", "Life"),
                    ("auto", "Auto"),
                    ("home", "Home"),
                    ("health", "Health"),
                    ("recreational_vehicle", "Recreational Vehicle"),
                    ("renters", "Renters"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="HouseHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "head_of_household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(crm.models.models.get_sentinel_user),
                        to="crm.client",
                    ),
                ),
            ],
        ),
    ]
