# Generated by Django 5.2.1 on 2025-09-15 16:04

import crm.models.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0017_alter_policy_policy_type_household"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="households",
                to="crm.household",
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="head_of_household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(crm.models.models.get_sentinel_user),
                related_name="households_hoh",
                to="crm.client",
            ),
        ),
    ]
