# Generated by Django 5.2.1 on 2025-09-16 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0018_client_household_alter_household_head_of_household"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="household",
                to="crm.household",
            ),
        ),
    ]
