# Generated by Django 5.2.1 on 2025-09-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0019_alter_client_household"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="household_members", to="crm.client"
            ),
        ),
    ]
