# Generated by Django 5.2.1 on 2025-09-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0020_household_members"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="household",),
    ]
