# Generated by Django 5.2.1 on 2025-09-22 22:47

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0021_remove_client_household"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="notes",
            field=prose.fields.RichTextField(blank=True, null=True),
        ),
    ]
