# Generated by Django 5.2.3 on 2025-10-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_household_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(blank=True, choices=[('life', 'Life'), ('auto', 'Auto'), ('home', 'Home'), ('health', 'Health'), ('recreational_vehicle', 'Recreational Vehicle'), ('renters', 'Renters'), ('business', 'Business')], max_length=50, null=True),
        ),
    ]
