# Generated by Django 6.0.1 on 2026-01-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_policy_policy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(blank=True, choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20, null=True),
        ),
    ]
